### ISSUE TITLE
Using list instead of dictionaries for tables in schema.yaml

### ISSUE THREAD

**Issue by TerseTears** [Iran-Open-Data/HBSIR#42]

**Comment by m-amin-alavian** [comment]
current structure:  
```yaml
household_information:
  instructions:
    - add_year
    - apply_order:
      - Year
      - ID
      - Season
      - Weight	

house_specifications:
  instructions:
    - add_year
```

proposed structure:  
```yaml
tables:
  - table_name: household_information:
    instructions:
      - add_year
      - apply_order:
        - Year
        - ID
        - Season
        - Weight	


  - table_name: house_specifications:
    instructions:
      - add_year
```
